import type { Metadata } from "next";
import { Grandstander } from "next/font/google";
import "./globals.css";

const font = Grandstander({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${font.className} antialiased h-full m-0 p-0 overflow-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
